<template>
	<div class="report">
		<h1>Validation report</h1>
		<ul>
			<li><b>Format:</b> glTF {{ info.version }}</li>
			<li><b>Generator:</b> {{ info.generator }}</li>
			<li v-if="info.extras?.title">
				<b>Title:</b>
				<span v-html="info.extras.title"></span>
			</li>
			<li v-if="info.extras?.author">
				<b>Author:</b>
				<span v-html="info.extras.author"></span>
			</li>
			<li v-if="info.extras?.license">
				<b>License:</b>
				<span v-html="info.extras.license"></span>
			</li>
			<li v-if="info.extras?.source">
				<b>Source:</b>
				<span v-html="info.extras.source"></span>
			</li>
			<li>
				<b>Stats:</b>
				<ul>
					<li>{{ info.drawCallCount || '0' }} draw calls</li>
					<li>{{ info.animationCount || '0' }} animations</li>
					<li>{{ info.materialCount || '0' }} materials</li>
					<li>{{ info.totalVertexCount || '0' }} vertices</li>
					<li>{{ info.totalTriangleCount || '0' }} triangles</li>
				</ul>
			</li>
			<li>
				<b>Extensions:</b>
				<ul>
					<template v-if="info.extensionsUsed?.length">
						<li v-for="extension in info.extensionsUsed" :key="extension">
							{{ extension }}
						</li>
					</template>
					<li v-else>None</li>
				</ul>
				<p v-if="info.extensionsUsed?.length">
					<i>
						NOTE: Extensions above are present in the model, but may or may not be
						recognized by this viewer. Any "UNSUPPORTED_EXTENSION" warnings below refer
						only to extensions that could not be scanned by the validation suite, and
						may still have rendered correctly. See:
						<a
							href="https://github.com/donmccurdy/three-gltf-viewer/issues/122"
							target="_blank"
						>
							three-gltf-viewer#122
						</a>
						.
					</i>
				</p>
			</li>
		</ul>
		<hr />
		<p>
			Report generated by
			<a href="https://github.com/KhronosGroup/glTF-Validator/">
				KhronosGroup/glTF-Validator
			</a>
			{{ validatorVersion }}.
		</p>

		<ValidatorTable v-if="issues.numErrors" :messages="errors" color="#f44336" title="Error" />
		<ValidatorTable
			v-if="issues.numWarnings"
			:messages="warnings"
			color="#f9a825"
			title="Warning"
		/>
		<ValidatorTable v-if="issues.numHints" :messages="hints" color="#8bc34a" title="Hint" />
		<ValidatorTable v-if="issues.numInfos" :messages="infos" color="#2196f3" title="Info" />
	</div>
</template>

<script setup lang="ts">
import ValidatorTable from './ValidatorTable.vue';

// 定义 info 对象内部的结构
interface InfoExtras {
	title?: string;
	author?: string;
	license?: string;
	source?: string;
}

interface ValidationInfo {
	version: string;
	generator: string;
	extras?: InfoExtras;
	drawCallCount?: number;
	animationCount?: number;
	materialCount?: number;
	totalVertexCount?: number;
	totalTriangleCount?: number;
	extensionsUsed?: string[];
}

// 定义 issues 对象内部的结构
interface ValidationIssues {
	numErrors?: number;
	numWarnings?: number;
	numHints?: number;
	numInfos?: number;
}

// 定义 Props 接口
defineProps<{
	info: ValidationInfo;
	validatorVersion: string;
	issues: ValidationIssues;
	errors: any[];
	warnings: any[];
	hints: any[];
	infos: any[];
}>();
</script>

<style scoped></style>
